name: example-environment
channels:
  - conda-forge
dependencies:
  - numpy
  - pandas
  - math==3.7.4
  - matplotlib
  - warning==2.7.16
  - sklearn==0.21.3
  - random==3.3.7
  - itertools==3.3.0
  - scipy
  - prettytable
